# Generated by Django 3.2.19 on 2023-06-30 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('proposal_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Aprovada', 'Aprovada'), ('Negada', 'Negada'), ('Em análise', 'Em análise')], default='Em análise', max_length=50)),
                ('human_analysis', models.CharField(choices=[('Aprovada', 'Aprovada'), ('Negada', 'Negada'), ('Em análise', 'Em análise')], default='Em análise', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProposalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(max_length=50)),
                ('required', models.BooleanField(default=False)),
                ('max_length', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProposalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=200, null=True)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emprestimo.proposalconfig')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emprestimo.proposal')),
            ],
        ),
        migrations.AddField(
            model_name='proposal',
            name='config',
            field=models.ManyToManyField(to='emprestimo.ProposalConfig'),
        ),
    ]
