# Generated by Django 3.2.19 on 2023-06-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0002_alter_proposal_human_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='document',
            field=models.CharField(default='999999', max_length=50),
        ),
    ]
